### ISSUE TITLE
`Check individual match fetching` is a flaky test

### ISSUE THREAD

**Issue by MrBartusek** [TheDrone7/shieldbow#15]
`Test Spectator v4 API > Check individual match fetching` seems to randomly fail. It works like 70% of the time, it's the only test that does that.

```
FAIL  tests/spectator.test.ts (26.859 s)
  Test Spectator v4 API
    √ Check fetching featured games (2 ms)
    × Check individual match fetching (2 ms)

  ● Test Spectator v4 API › Check individual match fetching

    TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters

      at RedirectableRequest.Object.<anonymous>.RedirectableRequest._performRequest (node_modules/follow-redirects/index.js:279:24)
      at new RedirectableRequest (node_modules/follow-redirects/index.js:61:8)
      at Object.request (node_modules/follow-redirects/index.js:511:14)
      at dispatchHttpRequest (node_modules/axios/lib/adapters/http.js:232:25)
      at httpAdapter (node_modules/axios/lib/adapters/http.js:48:10)
      at dispatchRequest (node_modules/axios/lib/core/dispatchRequest.js:58:10)
```

**Comment by TheDrone7** [comment]
Yeah this one's flaky because there is absolutely no way to guarantee for some player to be in-game at all times without first actually fetching their game state first.

**Comment by TheDrone7** [comment]
This should no longer be an issue now. The issue was some people having non unicode characters in their usernames and adding encodeURIComponent to the appropriate managers should fix this for good.
