### ISSUE TITLE
Fetching league entries not working

### ISSUE THREAD

**Issue by Proudyyyyy** [TheDrone7/shieldbow#53]
NOTE: I attached pastebin posts here, due to the fact that I didn't make it to put typescript code inside here without it being formatted wrong. And I already tried out the "code"-block option in the editor.

Client initialization:
https://pastebin.com/EJj3ph11

Rest of the script:
https://pastebin.com/tT13ptnu

Logs provided by regular outputs and the logger.
> [2023-04-11T01:29:08.902Z] DEBUG    :: Initializing client... logging enabled.
[2023-04-11T01:29:08.903Z] DEBUG    :: Order: version, locale, rate limiter, cache, storage, static data.
[2023-04-11T01:29:08.903Z] TRACE    :: Fetching latest version and locale from the API.
[2023-04-11T01:29:08.987Z] TRACE    :: Using version 13.7.1 and locale en_GB.
[2023-04-11T01:29:08.987Z] TRACE    :: Initializing the API rate limiter.
[2023-04-11T01:29:08.988Z] TRACE    :: Parsing caching configuration.
[2023-04-11T01:29:08.988Z] TRACE    :: Parsing storage configuration.
[2023-04-11T01:29:08.988Z] TRACE    :: Fetching seasons static data from DDragon.
[2023-04-11T01:29:09.055Z] TRACE    :: Fetching queues static data from DDragon.
[2023-04-11T01:29:09.076Z] TRACE    :: Fetching maps static data from DDragon.
[2023-04-11T01:29:09.099Z] TRACE    :: Fetching game modes static data from DDragon.
[2023-04-11T01:29:09.119Z] TRACE    :: Fetching game types static data from DDragon.
[2023-04-11T01:29:09.139Z] TRACE    :: Parsing fetched static data into defined interfaces.
[2023-04-11T01:29:09.140Z] DEBUG    :: Client initialized, now prefetching.
[2023-04-11T01:29:09.140Z] TRACE    :: Prefetch specified data from DDragon.
TypeError: Cannot read properties of undefined (reading 'league')
    at parseFetchOptions (/home/user/project-backend/node_modules/shieldbow/src/util/parseFetchOptions.ts:59:37)
    at LeagueManager.fetchByQueueAndTier (/home/user/project-backend/node_modules/shieldbow/src/managers/LeagueManager.ts:100:35)
    at file:///home/user/project-backend/index.ts:46:42
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by TheDrone7** [comment]
Closing this, #54 is the more appropriate version of the same issue.
