### ISSUE TITLE
[BUG] Unexpected end of JSON input

### ISSUE THREAD

**Issue by MrBartusek** [TheDrone7/shieldbow#6]
**Describe the bug**
Using getting started code from documentation results in an error

**Error**
Use `.catch()` to catch promise rejections or `try...catch` to catch any errors and paste the stack trace below

```
λ node dist/index.js
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at StorageManager.fetch ([...]\node_modules\shieldbow\dist\managers\StorageManager.js:66:21)
    at [...]\node_modules\shieldbow\dist\managers\ChampionManager.js:104:44
    at new Promise (<anonymous>)
    at ChampionManager._fetchLocalDamage ([...]\node_modules\shieldbow\dist\managers\ChampionManager.js:103:16)
    at [...]\node_modules\shieldbow\dist\managers\ChampionManager.js:135:51
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Node.JS version v16.13.0
 - Library version 1.3.0
- Typescript version 4.7.4

**Additional context**
Would be best to include a code snippet here to help reproduce the bug quickly.

```ts
client.initialize({
  region: 'euw' // defaults to 'na'
}).then(async () => {
  // After initialization, you can use the client to make requests
  // For example, lets fetch the following details of a summoner
  // - Summoner name, summoner level
  // - SoloQ ranking and LP
  // - Highest champion mastery
  
  const summoner = await client.summoners.fetchBySummonerName('TheDrone7');
  const leagueEntry = await summoner.fetchLeagueEntries();
  const championMastery = summoner.championMastery;
  
  const soloQ = leagueEntry.get('RANKED_SOLO_5x5')!;
  const highest = await championMastery.highest();
  
  console.log(`Summoner name: ${summoner.name} (level: ${summoner.level}).`);
  console.log(`SoloQ: ${soloQ.tier} ${soloQ.division} (${soloQ.lp} LP).`);
  console.log(`Highest champion mastery: ${highest.champion.name} (M${highest.level} ${highest.points} points).`);
});
```

**Comment by MrBartusek** [comment]
It seems like this happens when the initial data fetching process is interrupted and an empty file is created which causes this error. You can reproduce it by removing the content of any JSON file.

**Comment by TheDrone7** [comment]
I mean, that's a user error though. Fetching seems to be working fine.

**Comment by MrBartusek** [comment]
Yeah, but then, any corruption in cache files completely blocks an app from starting till someone manually removes cache files?
